apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulsar-console
  labels:
    app.kubernetes.io/name: pulsar-console
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pulsar-console
  labels:
    app.kubernetes.io/name: pulsar-console
rules: []  # No special permissions needed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pulsar-console
  labels:
    app.kubernetes.io/name: pulsar-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pulsar-console
subjects:
  - kind: ServiceAccount
    name: pulsar-console
